service: websocket
runtime: python
entrypoint: gunicorn -b :8080 ws:app --worker-class sanic.worker.GunicornWorker

runtime_config:
  python_version: 3

env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
threadsafe: yes

network:
  session_affinity: true
